/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NextCoach API
 * API para app NextCoach AI
 * OpenAPI spec version: 0.0.1
 */
import { customFetch } from "../../fetch"
export type GetHomeDate200TodayWorkoutDayWeekDay =
	(typeof GetHomeDate200TodayWorkoutDayWeekDay)[keyof typeof GetHomeDate200TodayWorkoutDayWeekDay]

export const GetHomeDate200TodayWorkoutDayWeekDay = {
	SUNDAY: "SUNDAY",
	MONDAY: "MONDAY",
	TUESDAY: "TUESDAY",
	WEDNESDAY: "WEDNESDAY",
	THURSDAY: "THURSDAY",
	FRIDAY: "FRIDAY",
	SATURDAY: "SATURDAY",
} as const

export type GetHomeDate200TodayWorkoutDay = {
	/** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
	workoutPlanId: string
	/** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
	id: string
	name: string
	isRest: boolean
	weekDay: GetHomeDate200TodayWorkoutDayWeekDay
	estimatedDurationInSeconds: number
	coverImageUrl?: string
	exercisesCount: number
}

export type GetHomeDate200ConsistencyByDay = {
	[key: string]: {
		workoutDayCompleted: boolean
		workoutDayStarted: boolean
	}
}

export type GetHomeDate200 = {
	/** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
	activeWorkoutPlanId: string
	todayWorkoutDay: GetHomeDate200TodayWorkoutDay
	workoutStreak: number
	consistencyByDay: GetHomeDate200ConsistencyByDay
}

export type GetHomeDate401 = {
	error: string
	code: string
}

export type GetHomeDate404 = {
	error: string
	code: string
}

export type GetHomeDate500 = {
	error: string
	code: string
}

/**
 * @nullable
 */
export type GetUserTrainData200 = {
	userId: string
	userName: string
	weightInGrams: number
	heightInCentimeters: number
	age: number
	/**
	 * @minimum 0
	 * @maximum 100
	 */
	bodyFatPercentage: number
} | null

export type GetUserTrainData401 = {
	error: string
	code: string
}

export type GetUserTrainData500 = {
	error: string
	code: string
}

export type UpsertUserTrainDataBody = {
	/** @minimum 0 */
	weightInGrams: number
	/** @minimum 0 */
	heightInCentimeters: number
	/** @minimum 0 */
	age: number
	/**
	 * @minimum 0
	 * @maximum 100
	 */
	bodyFatPercentage: number
}

export type UpsertUserTrainData200 = {
	userId: string
	weightInGrams: number
	heightInCentimeters: number
	age: number
	bodyFatPercentage: number
}

export type UpsertUserTrainData401 = {
	error: string
	code: string
}

export type UpsertUserTrainData500 = {
	error: string
	code: string
}

export type GetUserWorkoutStatsParams = {
	/**
	 * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
	 */
	from: string
	/**
	 * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
	 */
	to: string
}

export type GetUserWorkoutStats200ConsistencyByDay = {
	[key: string]: {
		workoutDayCompleted: boolean
		workoutDayStarted: boolean
	}
}

export type GetUserWorkoutStats200 = {
	workoutStreak: number
	consistencyByDay: GetUserWorkoutStats200ConsistencyByDay
	completedWorkoutsCount: number
	conclusionRate: number
	totalTimeInSeconds: number
}

export type GetUserWorkoutStats401 = {
	error: string
	code: string
}

export type GetUserWorkoutStats404 = {
	error: string
	code: string
}

export type GetUserWorkoutStats500 = {
	error: string
	code: string
}

export type ListWorkoutPlansParams = {
	active?: ListWorkoutPlansActive
}

export type ListWorkoutPlansActive =
	(typeof ListWorkoutPlansActive)[keyof typeof ListWorkoutPlansActive]

export const ListWorkoutPlansActive = {
	true: "true",
	false: "false",
} as const

export type ListWorkoutPlans200ItemWorkoutDaysItemWeekDay =
	(typeof ListWorkoutPlans200ItemWorkoutDaysItemWeekDay)[keyof typeof ListWorkoutPlans200ItemWorkoutDaysItemWeekDay]

export const ListWorkoutPlans200ItemWorkoutDaysItemWeekDay = {
	SUNDAY: "SUNDAY",
	MONDAY: "MONDAY",
	TUESDAY: "TUESDAY",
	WEDNESDAY: "WEDNESDAY",
	THURSDAY: "THURSDAY",
	FRIDAY: "FRIDAY",
	SATURDAY: "SATURDAY",
} as const

export type ListWorkoutPlans200ItemWorkoutDaysItemExercisesItem = {
	/** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
	id: string
	order: number
	name: string
	sets: number
	reps: number
	restTimeInSeconds: number
}

export type ListWorkoutPlans200ItemWorkoutDaysItem = {
	/** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
	id: string
	name: string
	weekDay: ListWorkoutPlans200ItemWorkoutDaysItemWeekDay
	isRest: boolean
	estimatedDurationInSeconds: number
	coverImageUrl?: string
	exercises: ListWorkoutPlans200ItemWorkoutDaysItemExercisesItem[]
}

export type ListWorkoutPlans200Item = {
	/** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
	id: string
	name: string
	isActive: boolean
	workoutDays: ListWorkoutPlans200ItemWorkoutDaysItem[]
}

export type ListWorkoutPlans401 = {
	error: string
	code: string
}

export type ListWorkoutPlans500 = {
	error: string
	code: string
}

export type CreateWorkoutPlanBodyWorkoutDaysItemWeekDay =
	(typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay]

export const CreateWorkoutPlanBodyWorkoutDaysItemWeekDay = {
	SUNDAY: "SUNDAY",
	MONDAY: "MONDAY",
	TUESDAY: "TUESDAY",
	WEDNESDAY: "WEDNESDAY",
	THURSDAY: "THURSDAY",
	FRIDAY: "FRIDAY",
	SATURDAY: "SATURDAY",
} as const

export type CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem = {
	id: string
	/** @minimum 0 */
	order: number
	/** @minLength 1 */
	name: string
	/** @minimum 1 */
	sets: number
	/** @minimum 1 */
	reps: number
	/** @minimum 1 */
	restTimeInSeconds: number
}

export type CreateWorkoutPlanBodyWorkoutDaysItem = {
	id: string
	/** @minLength 1 */
	name: string
	weekDay: CreateWorkoutPlanBodyWorkoutDaysItemWeekDay
	isRest?: boolean
	/** @minimum 1 */
	estimatedDurationInSeconds: number
	coverImageUrl?: string
	exercises: CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem[]
}

export type CreateWorkoutPlanBody = {
	/** @minLength 1 */
	name: string
	userId: string
	isActive: boolean
	createdAt: unknown
	workoutDays: CreateWorkoutPlanBodyWorkoutDaysItem[]
}

export type CreateWorkoutPlan201WorkoutDaysItemWeekDay =
	(typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay]

export const CreateWorkoutPlan201WorkoutDaysItemWeekDay = {
	SUNDAY: "SUNDAY",
	MONDAY: "MONDAY",
	TUESDAY: "TUESDAY",
	WEDNESDAY: "WEDNESDAY",
	THURSDAY: "THURSDAY",
	FRIDAY: "FRIDAY",
	SATURDAY: "SATURDAY",
} as const

export type CreateWorkoutPlan201WorkoutDaysItemExercisesItem = {
	/** @minimum 0 */
	order: number
	/** @minLength 1 */
	name: string
	/** @minimum 1 */
	sets: number
	/** @minimum 1 */
	reps: number
	/** @minimum 1 */
	restTimeInSeconds: number
}

export type CreateWorkoutPlan201WorkoutDaysItem = {
	/** @minLength 1 */
	name: string
	weekDay: CreateWorkoutPlan201WorkoutDaysItemWeekDay
	isRest: boolean
	/** @minimum 1 */
	estimatedDurationInSeconds: number
	coverImageUrl?: unknown
	exercises: CreateWorkoutPlan201WorkoutDaysItemExercisesItem[]
}

export type CreateWorkoutPlan201 = {
	/** @minLength 1 */
	name: string
	workoutDays: CreateWorkoutPlan201WorkoutDaysItem[]
}

export type CreateWorkoutPlan400 = {
	error: string
	code: string
}

export type CreateWorkoutPlan401 = {
	error: string
	code: string
}

export type CreateWorkoutPlan404 = {
	error: string
	code: string
}

export type CreateWorkoutPlan500 = {
	error: string
	code: string
}

export type GetWorkoutPlan200WorkoutDaysItemWeekDay =
	(typeof GetWorkoutPlan200WorkoutDaysItemWeekDay)[keyof typeof GetWorkoutPlan200WorkoutDaysItemWeekDay]

export const GetWorkoutPlan200WorkoutDaysItemWeekDay = {
	SUNDAY: "SUNDAY",
	MONDAY: "MONDAY",
	TUESDAY: "TUESDAY",
	WEDNESDAY: "WEDNESDAY",
	THURSDAY: "THURSDAY",
	FRIDAY: "FRIDAY",
	SATURDAY: "SATURDAY",
} as const

export type GetWorkoutPlan200WorkoutDaysItem = {
	/** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
	id: string
	weekDay: GetWorkoutPlan200WorkoutDaysItemWeekDay
	name: string
	isRest: boolean
	coverImageUrl?: string
	estimatedDurationInSeconds: number
	exercisesCount: number
}

export type GetWorkoutPlan200 = {
	/** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
	id: string
	name: string
	workoutDays: GetWorkoutPlan200WorkoutDaysItem[]
}

export type GetWorkoutPlan401 = {
	error: string
	code: string
}

export type GetWorkoutPlan404 = {
	error: string
	code: string
}

export type GetWorkoutPlan500 = {
	error: string
	code: string
}

export type GetWorkoutDay200WeekDay =
	(typeof GetWorkoutDay200WeekDay)[keyof typeof GetWorkoutDay200WeekDay]

export const GetWorkoutDay200WeekDay = {
	SUNDAY: "SUNDAY",
	MONDAY: "MONDAY",
	TUESDAY: "TUESDAY",
	WEDNESDAY: "WEDNESDAY",
	THURSDAY: "THURSDAY",
	FRIDAY: "FRIDAY",
	SATURDAY: "SATURDAY",
} as const

export type GetWorkoutDay200ExercisesItem = {
	/** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
	id: string
	name: string
	order: number
	/** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
	workoutDayId: string
	sets: number
	reps: number
	restTimeInSeconds: number
}

export type GetWorkoutDay200SessionsItem = {
	/** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
	id: string
	/** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
	workoutDayId: string
	/** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$ */
	startedAt?: string
	/** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$ */
	completedAt?: string
}

export type GetWorkoutDay200 = {
	/** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
	id: string
	name: string
	isRest: boolean
	coverImageUrl?: string
	estimatedDurationInSeconds: number
	weekDay: GetWorkoutDay200WeekDay
	exercises: GetWorkoutDay200ExercisesItem[]
	sessions: GetWorkoutDay200SessionsItem[]
}

export type GetWorkoutDay401 = {
	error: string
	code: string
}

export type GetWorkoutDay404 = {
	error: string
	code: string
}

export type GetWorkoutDay500 = {
	error: string
	code: string
}

export type StartWorkoutSession201 = {
	/** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
	userWorkoutSessionId: string
}

export type StartWorkoutSession401 = {
	error: string
	code: string
}

export type StartWorkoutSession404 = {
	error: string
	code: string
}

export type StartWorkoutSession409 = {
	error: string
	code: string
}

export type StartWorkoutSession422 = {
	error: string
	code: string
}

export type StartWorkoutSession500 = {
	error: string
	code: string
}

export type UpdateWorkoutSessionBody = {
	/** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
	completedAt: string
}

export type UpdateWorkoutSession200 = {
	/** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
	id: string
	/** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
	startedAt: string
	/** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
	completedAt: string
}

export type UpdateWorkoutSession401 = {
	error: string
	code: string
}

export type UpdateWorkoutSession404 = {
	error: string
	code: string
}

export type UpdateWorkoutSession500 = {
	error: string
	code: string
}

export type Get200 = {
	message: string
}

/**
 * @summary Get home page data
 */
export type getHomeDateResponse200 = {
	data: GetHomeDate200
	status: 200
}

export type getHomeDateResponse401 = {
	data: GetHomeDate401
	status: 401
}

export type getHomeDateResponse404 = {
	data: GetHomeDate404
	status: 404
}

export type getHomeDateResponse500 = {
	data: GetHomeDate500
	status: 500
}

export type getHomeDateResponseSuccess = getHomeDateResponse200 & {
	headers: Headers
}
export type getHomeDateResponseError = (
	| getHomeDateResponse401
	| getHomeDateResponse404
	| getHomeDateResponse500
) & {
	headers: Headers
}

export type getHomeDateResponse =
	| getHomeDateResponseSuccess
	| getHomeDateResponseError

export const getGetHomeDateUrl = (date: string) => {
	return `/home/${date}`
}

export const getHomeDate = async (
	date: string,
	options?: RequestInit,
): Promise<getHomeDateResponse> => {
	return customFetch<getHomeDateResponse>(getGetHomeDateUrl(date), {
		...options,
		method: "GET",
	})
}

/**
 * @summary Get user train data
 */
export type getUserTrainDataResponse200 = {
	data: GetUserTrainData200
	status: 200
}

export type getUserTrainDataResponse401 = {
	data: GetUserTrainData401
	status: 401
}

export type getUserTrainDataResponse500 = {
	data: GetUserTrainData500
	status: 500
}

export type getUserTrainDataResponseSuccess = getUserTrainDataResponse200 & {
	headers: Headers
}
export type getUserTrainDataResponseError = (
	| getUserTrainDataResponse401
	| getUserTrainDataResponse500
) & {
	headers: Headers
}

export type getUserTrainDataResponse =
	| getUserTrainDataResponseSuccess
	| getUserTrainDataResponseError

export const getGetUserTrainDataUrl = () => {
	return `/me/`
}

export const getUserTrainData = async (
	options?: RequestInit,
): Promise<getUserTrainDataResponse> => {
	return customFetch<getUserTrainDataResponse>(getGetUserTrainDataUrl(), {
		...options,
		method: "GET",
	})
}

/**
 * @summary Upsert user train data
 */
export type upsertUserTrainDataResponse200 = {
	data: UpsertUserTrainData200
	status: 200
}

export type upsertUserTrainDataResponse401 = {
	data: UpsertUserTrainData401
	status: 401
}

export type upsertUserTrainDataResponse500 = {
	data: UpsertUserTrainData500
	status: 500
}

export type upsertUserTrainDataResponseSuccess =
	upsertUserTrainDataResponse200 & {
		headers: Headers
	}
export type upsertUserTrainDataResponseError = (
	| upsertUserTrainDataResponse401
	| upsertUserTrainDataResponse500
) & {
	headers: Headers
}

export type upsertUserTrainDataResponse =
	| upsertUserTrainDataResponseSuccess
	| upsertUserTrainDataResponseError

export const getUpsertUserTrainDataUrl = () => {
	return `/me/`
}

export const upsertUserTrainData = async (
	upsertUserTrainDataBody: UpsertUserTrainDataBody,
	options?: RequestInit,
): Promise<upsertUserTrainDataResponse> => {
	return customFetch<upsertUserTrainDataResponse>(
		getUpsertUserTrainDataUrl(),
		{
			...options,
			method: "PUT",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(upsertUserTrainDataBody),
		},
	)
}

/**
 * @summary Get user workout stats
 */
export type getUserWorkoutStatsResponse200 = {
	data: GetUserWorkoutStats200
	status: 200
}

export type getUserWorkoutStatsResponse401 = {
	data: GetUserWorkoutStats401
	status: 401
}

export type getUserWorkoutStatsResponse404 = {
	data: GetUserWorkoutStats404
	status: 404
}

export type getUserWorkoutStatsResponse500 = {
	data: GetUserWorkoutStats500
	status: 500
}

export type getUserWorkoutStatsResponseSuccess =
	getUserWorkoutStatsResponse200 & {
		headers: Headers
	}
export type getUserWorkoutStatsResponseError = (
	| getUserWorkoutStatsResponse401
	| getUserWorkoutStatsResponse404
	| getUserWorkoutStatsResponse500
) & {
	headers: Headers
}

export type getUserWorkoutStatsResponse =
	| getUserWorkoutStatsResponseSuccess
	| getUserWorkoutStatsResponseError

export const getGetUserWorkoutStatsUrl = (
	params: GetUserWorkoutStatsParams,
) => {
	const normalizedParams = new URLSearchParams()

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(
				key,
				value === null ? "null" : value.toString(),
			)
		}
	})

	const stringifiedParams = normalizedParams.toString()

	return stringifiedParams.length > 0
		? `/stats/?${stringifiedParams}`
		: `/stats/`
}

export const getUserWorkoutStats = async (
	params: GetUserWorkoutStatsParams,
	options?: RequestInit,
): Promise<getUserWorkoutStatsResponse> => {
	return customFetch<getUserWorkoutStatsResponse>(
		getGetUserWorkoutStatsUrl(params),
		{
			...options,
			method: "GET",
		},
	)
}

/**
 * @summary List workout plans
 */
export type listWorkoutPlansResponse200 = {
	data: ListWorkoutPlans200Item[]
	status: 200
}

export type listWorkoutPlansResponse401 = {
	data: ListWorkoutPlans401
	status: 401
}

export type listWorkoutPlansResponse500 = {
	data: ListWorkoutPlans500
	status: 500
}

export type listWorkoutPlansResponseSuccess = listWorkoutPlansResponse200 & {
	headers: Headers
}
export type listWorkoutPlansResponseError = (
	| listWorkoutPlansResponse401
	| listWorkoutPlansResponse500
) & {
	headers: Headers
}

export type listWorkoutPlansResponse =
	| listWorkoutPlansResponseSuccess
	| listWorkoutPlansResponseError

export const getListWorkoutPlansUrl = (params?: ListWorkoutPlansParams) => {
	const normalizedParams = new URLSearchParams()

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(
				key,
				value === null ? "null" : value.toString(),
			)
		}
	})

	const stringifiedParams = normalizedParams.toString()

	return stringifiedParams.length > 0
		? `/workout-plans/?${stringifiedParams}`
		: `/workout-plans/`
}

export const listWorkoutPlans = async (
	params?: ListWorkoutPlansParams,
	options?: RequestInit,
): Promise<listWorkoutPlansResponse> => {
	return customFetch<listWorkoutPlansResponse>(
		getListWorkoutPlansUrl(params),
		{
			...options,
			method: "GET",
		},
	)
}

/**
 * @summary Create a workout plan
 */
export type createWorkoutPlanResponse201 = {
	data: CreateWorkoutPlan201
	status: 201
}

export type createWorkoutPlanResponse400 = {
	data: CreateWorkoutPlan400
	status: 400
}

export type createWorkoutPlanResponse401 = {
	data: CreateWorkoutPlan401
	status: 401
}

export type createWorkoutPlanResponse404 = {
	data: CreateWorkoutPlan404
	status: 404
}

export type createWorkoutPlanResponse500 = {
	data: CreateWorkoutPlan500
	status: 500
}

export type createWorkoutPlanResponseSuccess = createWorkoutPlanResponse201 & {
	headers: Headers
}
export type createWorkoutPlanResponseError = (
	| createWorkoutPlanResponse400
	| createWorkoutPlanResponse401
	| createWorkoutPlanResponse404
	| createWorkoutPlanResponse500
) & {
	headers: Headers
}

export type createWorkoutPlanResponse =
	| createWorkoutPlanResponseSuccess
	| createWorkoutPlanResponseError

export const getCreateWorkoutPlanUrl = () => {
	return `/workout-plans/`
}

export const createWorkoutPlan = async (
	createWorkoutPlanBody: CreateWorkoutPlanBody,
	options?: RequestInit,
): Promise<createWorkoutPlanResponse> => {
	return customFetch<createWorkoutPlanResponse>(getCreateWorkoutPlanUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(createWorkoutPlanBody),
	})
}

/**
 * @summary Get a workout plan
 */
export type getWorkoutPlanResponse200 = {
	data: GetWorkoutPlan200
	status: 200
}

export type getWorkoutPlanResponse401 = {
	data: GetWorkoutPlan401
	status: 401
}

export type getWorkoutPlanResponse404 = {
	data: GetWorkoutPlan404
	status: 404
}

export type getWorkoutPlanResponse500 = {
	data: GetWorkoutPlan500
	status: 500
}

export type getWorkoutPlanResponseSuccess = getWorkoutPlanResponse200 & {
	headers: Headers
}
export type getWorkoutPlanResponseError = (
	| getWorkoutPlanResponse401
	| getWorkoutPlanResponse404
	| getWorkoutPlanResponse500
) & {
	headers: Headers
}

export type getWorkoutPlanResponse =
	| getWorkoutPlanResponseSuccess
	| getWorkoutPlanResponseError

export const getGetWorkoutPlanUrl = (workoutPlanId: string) => {
	return `/workout-plans/${workoutPlanId}`
}

export const getWorkoutPlan = async (
	workoutPlanId: string,
	options?: RequestInit,
): Promise<getWorkoutPlanResponse> => {
	return customFetch<getWorkoutPlanResponse>(
		getGetWorkoutPlanUrl(workoutPlanId),
		{
			...options,
			method: "GET",
		},
	)
}

/**
 * @summary Get a workout day
 */
export type getWorkoutDayResponse200 = {
	data: GetWorkoutDay200
	status: 200
}

export type getWorkoutDayResponse401 = {
	data: GetWorkoutDay401
	status: 401
}

export type getWorkoutDayResponse404 = {
	data: GetWorkoutDay404
	status: 404
}

export type getWorkoutDayResponse500 = {
	data: GetWorkoutDay500
	status: 500
}

export type getWorkoutDayResponseSuccess = getWorkoutDayResponse200 & {
	headers: Headers
}
export type getWorkoutDayResponseError = (
	| getWorkoutDayResponse401
	| getWorkoutDayResponse404
	| getWorkoutDayResponse500
) & {
	headers: Headers
}

export type getWorkoutDayResponse =
	| getWorkoutDayResponseSuccess
	| getWorkoutDayResponseError

export const getGetWorkoutDayUrl = (
	workoutPlanId: string,
	workoutDayId: string,
) => {
	return `/workout-plans/${workoutPlanId}/days/${workoutDayId}`
}

export const getWorkoutDay = async (
	workoutPlanId: string,
	workoutDayId: string,
	options?: RequestInit,
): Promise<getWorkoutDayResponse> => {
	return customFetch<getWorkoutDayResponse>(
		getGetWorkoutDayUrl(workoutPlanId, workoutDayId),
		{
			...options,
			method: "GET",
		},
	)
}

/**
 * @summary Start a workout session
 */
export type startWorkoutSessionResponse201 = {
	data: StartWorkoutSession201
	status: 201
}

export type startWorkoutSessionResponse401 = {
	data: StartWorkoutSession401
	status: 401
}

export type startWorkoutSessionResponse404 = {
	data: StartWorkoutSession404
	status: 404
}

export type startWorkoutSessionResponse409 = {
	data: StartWorkoutSession409
	status: 409
}

export type startWorkoutSessionResponse422 = {
	data: StartWorkoutSession422
	status: 422
}

export type startWorkoutSessionResponse500 = {
	data: StartWorkoutSession500
	status: 500
}

export type startWorkoutSessionResponseSuccess =
	startWorkoutSessionResponse201 & {
		headers: Headers
	}
export type startWorkoutSessionResponseError = (
	| startWorkoutSessionResponse401
	| startWorkoutSessionResponse404
	| startWorkoutSessionResponse409
	| startWorkoutSessionResponse422
	| startWorkoutSessionResponse500
) & {
	headers: Headers
}

export type startWorkoutSessionResponse =
	| startWorkoutSessionResponseSuccess
	| startWorkoutSessionResponseError

export const getStartWorkoutSessionUrl = (
	workoutPlanId: string,
	workoutDayId: string,
) => {
	return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions`
}

export const startWorkoutSession = async (
	workoutPlanId: string,
	workoutDayId: string,
	options?: RequestInit,
): Promise<startWorkoutSessionResponse> => {
	return customFetch<startWorkoutSessionResponse>(
		getStartWorkoutSessionUrl(workoutPlanId, workoutDayId),
		{
			...options,
			method: "POST",
		},
	)
}

/**
 * @summary Update a workout session
 */
export type updateWorkoutSessionResponse200 = {
	data: UpdateWorkoutSession200
	status: 200
}

export type updateWorkoutSessionResponse401 = {
	data: UpdateWorkoutSession401
	status: 401
}

export type updateWorkoutSessionResponse404 = {
	data: UpdateWorkoutSession404
	status: 404
}

export type updateWorkoutSessionResponse500 = {
	data: UpdateWorkoutSession500
	status: 500
}

export type updateWorkoutSessionResponseSuccess =
	updateWorkoutSessionResponse200 & {
		headers: Headers
	}
export type updateWorkoutSessionResponseError = (
	| updateWorkoutSessionResponse401
	| updateWorkoutSessionResponse404
	| updateWorkoutSessionResponse500
) & {
	headers: Headers
}

export type updateWorkoutSessionResponse =
	| updateWorkoutSessionResponseSuccess
	| updateWorkoutSessionResponseError

export const getUpdateWorkoutSessionUrl = (
	workoutPlanId: string,
	workoutDayId: string,
	sessionId: string,
) => {
	return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions/${sessionId}`
}

export const updateWorkoutSession = async (
	workoutPlanId: string,
	workoutDayId: string,
	sessionId: string,
	updateWorkoutSessionBody: UpdateWorkoutSessionBody,
	options?: RequestInit,
): Promise<updateWorkoutSessionResponse> => {
	return customFetch<updateWorkoutSessionResponse>(
		getUpdateWorkoutSessionUrl(workoutPlanId, workoutDayId, sessionId),
		{
			...options,
			method: "PATCH",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(updateWorkoutSessionBody),
		},
	)
}

/**
 * @summary Chat with AI personal trainer
 */
export type chatAiPersonalTrainerResponse200 = {
	data: void
	status: 200
}

export type chatAiPersonalTrainerResponseSuccess =
	chatAiPersonalTrainerResponse200 & {
		headers: Headers
	}
export type chatAiPersonalTrainerResponse = chatAiPersonalTrainerResponseSuccess

export const getChatAiPersonalTrainerUrl = () => {
	return `/ai/`
}

export const chatAiPersonalTrainer = async (
	options?: RequestInit,
): Promise<chatAiPersonalTrainerResponse> => {
	return customFetch<chatAiPersonalTrainerResponse>(
		getChatAiPersonalTrainerUrl(),
		{
			...options,
			method: "POST",
		},
	)
}

/**
 * Next Coach AI
 */
export type getResponse200 = {
	data: Get200
	status: 200
}

export type getResponseSuccess = getResponse200 & {
	headers: Headers
}
export type getResponse = getResponseSuccess

export const getGetUrl = () => {
	return `/`
}

export const get = async (options?: RequestInit): Promise<getResponse> => {
	return customFetch<getResponse>(getGetUrl(), {
		...options,
		method: "GET",
	})
}
